when:
  - event: push
    branch: main

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: gitea.hhlab.home.arpa
      repo: gitea.hhlab.home.arpa/eduardo/daysuntil
      platforms: linux/amd64,linux/arm64
      tags:
        - latest
        - ${CI_COMMIT_SHA}
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_token
