name: Build and Deploy to staging (box)

on:
  push:
    branches: [box]
    tags: ["*"]

jobs:
  server_build_and_trigger_deploy:
    if: github.ref == 'refs/heads/box'
    uses: eduardo/ci-templates/.gitea/workflows/build-and-trigger-deploy.yml@main
    with:
      image_name: gitea.mediumsizedrobots.com/eduardo/daysuntil
      context: server
      dockerfile: server/Dockerfile
      platforms: linux/amd64,linux/arm64
      go_test: true
      go_test_path: ./...
      host: rpi-box-01
      nix_file: rpi-box-01/nixos/daysuntil.nix
      env_var: DAYSUNTIL_IMAGE
      health_url: https://daysuntil.mediumsizedrobots.com/api/version
    secrets: inherit

  web_build_and_trigger_deploy:
    if: github.ref == 'refs/heads/box'
    uses: eduardo/ci-templates/.gitea/workflows/build-and-trigger-deploy.yml@main
    with:
      image_name: gitea.mediumsizedrobots.com/eduardo/daysuntil-web
      context: web
      dockerfile: web/Dockerfile
      platforms: linux/amd64,linux/arm64
      host: rpi-box-01
      nix_file: rpi-box-01/nixos/daysuntil-web.nix
      env_var: DAYSUNTIL_WEB_IMAGE
      health_url: https://daysuntil.mediumsizedrobots.com/
    secrets: inherit
